engines:
    phpmd:
        enabled: true
        checks:
            Naming/ShortVariable:
            enabled: false
        config:
            file_extensions: "php"

    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"

    duplication:
        enabled: true
        config:
            languages:
                - php:

ratings:
    paths:
        - "src/**.php"

exclude_paths:
    - "test/**"
    - "vendor/**"
    - "view/anax/v2/dev/**"
    - "view/anax/v2/layout/**"
    - "htdocs/cimage/**"
    - "config/navbar/**"
    - "src/Navigation/**"
    - "src/Book/**"
    - "view/anax/v2/book/**"
